### ISSUE TITLE
CatchAtAge: Faulty CAA reports for gear group when missing age and length samples

### ISSUE THREAD

**Issue by BergenCalling** [StoXProject/RstoxFDA#111]
CAA for particular gear group reported outside of "Low" and "High".

**Comment by edvinf** [comment]
It is weird, but not impossible, for the mean to lie outside the reported intervals. This can happen for instance with spikes in the simulation, in which case it could be detectable from traceplots. Since this is for a cell with no data support, convergence issues are likely explanations.

I would suggest checking traceplots for issues in the relevant age groups.

Consider for instance the example:
distr <- c(rnorm(20,1,.1),1e6)
mean(distr)
quantile(distr,c(.05,.95))

which likely will illustrate the case.

**Comment by BergenCalling** [comment]
It goes for all the age groups for that particular combination of area and gear. When calculating CAA*mean weight it does not add up to reported catch

**Comment by edvinf** [comment]
Usually convergence issues are manifested for particular age groups, but there are some parameters that are not age-group specific that may have failed to converge. 

If traceplots do not indicate convergence problems, I could analyse the data to see if there are indications of convergence issues that we do not have support for detecting. You could for instance upload the output from RunRecaModels, and indicate the gear and area with problems.

**Comment by BergenCalling** [comment]
I ran the project with 4000 burnin. Now the CAA for Gillnet Area IIa is within the "Low" and "High" but the CAA*mean weight is still far from the reported catch for Gillnet in that area. I have uploaded the output from RunRecaModels
[CatchAtAge.txt](https://github.com/StoXProject/RstoxFDA/files/14994092/CatchAtAge.txt)
[GroupingVariables.txt](https://github.com/StoXProject/RstoxFDA/files/14994093/GroupingVariables.txt)
[MeanLength.txt](https://github.com/StoXProject/RstoxFDA/files/14994094/MeanLength.txt)
[MeanWeight.txt](https://github.com/StoXProject/RstoxFDA/files/14994095/MeanWeight.txt)

**Comment by BergenCalling** [comment]
And this is the traceplots
[PlotPosteriorTracesData.pdf](https://github.com/StoXProject/RstoxFDA/files/14994116/PlotPosteriorTracesData.pdf)

**Comment by edvinf** [comment]
MeanWeight shows indications of non-convergence for most age-groups. The age groups spike in the same iteration, which indicate that some effect that is not age-group specific has issues.

I don't think we need to fix anything with how these are plotted. Means outside the intervals are correct representations of these non-converged simulations, and served as a signal that the simulation had issues. In stead we should take this issue as an indication that we could need better diagnostic tools or more automated warnings about convergence issues.

Some open issues that are not yet prioritized for development may help detecting and addressing convergence issues:
https://github.com/StoXProject/RstoxFDA/issues/91
https://github.com/StoXProject/RstoxFDA/issues/89

Particularly #89 could have been helpful in this case.

For cells with no samples, convergence is expected to be slow, and interpretation is not necessarily more reliable than other approaches that approximate age distribution. For instance, the models may in stead be parameterised on coarser cells than what reports are generated for. Effectively assuming the age-distribution etc. to apply to a larger part of the fishery, but using more specific landing statistics to calculate total catch in numbers.
