### ISSUE TITLE
JSON schema validation fails when CarNeighbours contains CarValue instead of CarValues

### ISSUE THREAD

**Issue by arnejohannesholmin** [StoXProject/RstoxFDA#90]
There seems to be a discrepancy between the JSON schema of CarNeighbours in [(processDataSchema.json)](https://github.com/StoXProject/RstoxFDA/blob/master/inst/formats/processDataSchema.json), which requires the element "CarValues" (plural), and the loadCarNeighboursFile() used by DefineCarNeighbours(), which reads "CarValue" (singular), and possibly other functions.

The consequence is that a project.json with "CarValue" does not open in StoX.

**Comment by edvinf** [comment]
I will standardize on 'CarValue'. Since both are used by different function, and since 'CarValue' is semantically more appealing, since the table maps one CarValue to one or more neighbours. I will leave downstream functions and the schema accepting both variants.

**Comment by edvinf** [comment]
I will standardize on 'CarValue'. Since both are used by different function, and since 'CarValue' is semantically more appealing, since the table maps one CarValue to one or more neighbours. I will leave downstream functions and the schema accepting both variants.
